Repository googleapis/java-monitoring-dashboards, pull requests merged in 2020-08, with the labels that each got.

#156 chore(docs): add cloud-RAD
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#158 chore: regenerate common templates
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/dependencies.sh
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#162 feat: promote to 1.0.0
  .repo-metadata.json
  README.md
Labels: cla: yes

#166 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#170 samples: add presubmit lint check
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#171 build: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: monitoring, cla: yes, context: full
