Repository googleapis/java-monitoring-dashboards, pull requests merged in 2020-09, with the labels that each got.

#177 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: monitoring, cla: yes, context: full

#179 chore: regenerate common templates
  .github/CODEOWNERS
  README.md
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: partial

#195 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: monitoring, automerge, cla: yes

#200 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#202 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
