Repository googleapis/java-monitoring-dashboards, pull requests merged in 2020-06, with the labels that each got.

#117 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#119 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#118 docs: change relative URLs to absolute URLs to fix broken links.
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/Aggregation.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/TimeSeriesFilter.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/TimeSeriesFilterOrBuilder.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/TimeSeriesFilterRatio.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/TimeSeriesQuery.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/TimeSeriesQueryOrBuilder.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/proto/google/monitoring/dashboard/v1/common.proto
  proto-google-cloud-monitoring-dashboard-v1/src/main/proto/google/monitoring/dashboard/v1/metrics.proto
  synth.metadata
Labels: automerge, cla: yes, context: full

#124 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#126 feat: add support for secondary_aggregation and Monitoring Query Language.
  google-cloud-monitoring-dashboard/src/main/java/com/google/cloud/monitoring/dashboard/v1/DashboardsServiceClient.java
  google-cloud-monitoring-dashboard/src/main/java/com/google/cloud/monitoring/dashboard/v1/package-info.java
  google-cloud-monitoring-dashboard/src/main/java/com/google/cloud/monitoring/dashboard/v1/stub/DashboardsServiceStub.java
  google-cloud-monitoring-dashboard/src/main/java/com/google/cloud/monitoring/dashboard/v1/stub/GrpcDashboardsServiceCallableFactory.java
  google-cloud-monitoring-dashboard/src/main/java/com/google/cloud/monitoring/dashboard/v1/stub/GrpcDashboardsServiceStub.java
  google-cloud-monitoring-dashboard/src/test/java/com/google/cloud/monitoring/dashboard/v1/DashboardsServiceClientTest.java
  proto-google-cloud-monitoring-dashboard-v1/clirr-ignored-differences.xml
  proto-google-cloud-monitoring-dashboard-v1/pom.xml
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/Aggregation.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/AggregationOrBuilder.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/CommonProto.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/CreateDashboardRequest.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/CreateDashboardRequestOrBuilder.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/Dashboard.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/DashboardName.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/DashboardOrBuilder.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/DashboardsProto.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/DashboardsServiceProto.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/DeleteDashboardRequest.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/DeleteDashboardRequestOrBuilder.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/DrilldownsProto.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/GetDashboardRequest.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/GetDashboardRequestOrBuilder.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/ListDashboardsRequest.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/ListDashboardsRequestOrBuilder.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/ListDashboardsResponse.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/ListDashboardsResponseOrBuilder.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/MetricsProto.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/PickTimeSeriesFilter.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/PickTimeSeriesFilterOrBuilder.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/ProjectName.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/Scorecard.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/ScorecardOrBuilder.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/ScorecardProto.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/StatisticalTimeSeriesFilter.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/TimeSeriesFilter.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/TimeSeriesFilterOrBuilder.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/TimeSeriesFilterRatio.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/TimeSeriesFilterRatioOrBuilder.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/TimeSeriesQuery.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/TimeSeriesQueryOrBuilder.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/XyChart.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/XyChartOrBuilder.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/XyChartProto.java
  proto-google-cloud-monitoring-dashboard-v1/src/main/proto/google/monitoring/dashboard/v1/common.proto
  proto-google-cloud-monitoring-dashboard-v1/src/main/proto/google/monitoring/dashboard/v1/dashboard.proto
  proto-google-cloud-monitoring-dashboard-v1/src/main/proto/google/monitoring/dashboard/v1/dashboards_service.proto
  proto-google-cloud-monitoring-dashboard-v1/src/main/proto/google/monitoring/dashboard/v1/drilldowns.proto
  proto-google-cloud-monitoring-dashboard-v1/src/main/proto/google/monitoring/dashboard/v1/layouts.proto
  proto-google-cloud-monitoring-dashboard-v1/src/main/proto/google/monitoring/dashboard/v1/metrics.proto
  proto-google-cloud-monitoring-dashboard-v1/src/main/proto/google/monitoring/dashboard/v1/scorecard.proto
  proto-google-cloud-monitoring-dashboard-v1/src/main/proto/google/monitoring/dashboard/v1/service.proto
  proto-google-cloud-monitoring-dashboard-v1/src/main/proto/google/monitoring/dashboard/v1/text.proto
  proto-google-cloud-monitoring-dashboard-v1/src/main/proto/google/monitoring/dashboard/v1/widget.proto
  proto-google-cloud-monitoring-dashboard-v1/src/main/proto/google/monitoring/dashboard/v1/xychart.proto
  synth.metadata
Labels: automerge, cla: yes, context: full

#133 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#136 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-monitoring-dashboard/pom.xml
  grpc-google-cloud-monitoring-dashboard-v1/pom.xml
  pom.xml
  proto-google-cloud-monitoring-dashboard-v1/pom.xml
Labels: cla: yes

#146 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
