Repository googleapis/java-monitoring-dashboards, pull requests merged in 2021-07, with the labels that each got.

#409 chore: remove distributionManagement section
  pom.xml
Labels: api: monitoring, automerge, cla: yes

#410 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: monitoring, automerge, cla: yes

#412 chore: remove distributionManagement section
  google-cloud-monitoring-dashboard-bom/pom.xml
Labels: api: monitoring, automerge, cla: yes

#414 chore: remove All rights reserved clause from java.header
  java.header
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full

#417 chore: add dependencyDashboardLabels to renovate.json
  renovate.json
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full

#418 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: monitoring, automerge, cla: yes

#419 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/sync-repo-settings.yaml
  google-cloud-monitoring-dashboard-bom/pom.xml
  google-cloud-monitoring-dashboard/pom.xml
  google-cloud-monitoring-dashboard/src/main/java/com/google/cloud/monitoring/dashboard/v1/DashboardsServiceClient.java
  grpc-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/DashboardsServiceGrpc.java
  owlbot.py
  pom.xml
  proto-google-cloud-monitoring-dashboard-v1/src/main/proto/google/monitoring/dashboard/v1/dashboards_service.proto
  synth.py
  versions.txt
Labels: api: monitoring, automerge, cla: yes

#425 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: monitoring, automerge, cla: yes, kokoro:force-run

#428 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: monitoring, automerge, cla: yes

#429 feat: configure initial sp version
  .github/workflows/ci.yaml
Labels: api: monitoring, automerge, cla: yes
