Repository googleapis/java-monitoring-dashboards, pull requests merged in 2021-05, with the labels that each got.

#366 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: none

#367 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: monitoring, automerge, cla: yes

#368 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full

#371 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full

#376 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: monitoring, automerge, cla: yes

#377 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full

#379 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full

#382 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full
